### ISSUE TITLE
Updating (original) distributed page gives 500 error "NetworkSiteConnection::__construct() must be an instance of WP_Site, null given"

### ISSUE THREAD

**Issue by mitchmusarra** [10up/distributor#160]
This 500 error occurs when updating a distributed page over wp multi-site with visual composer elements used.

Updating regular (original) distributed pages (no VC elements or just plain text) does not produce an error.

```
2018/07/09 08:07:53 [error] 998#998: *23618 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Distributor\InternalConnections\NetworkSiteConnection::__construct() must be an instance of WP_Site, null given, called in /var/www/REMOVED/wp-content/plugins/distributor-master/includes/classes/InternalConnections/NetworkSiteConnection.php on line 496 and defined in /var/www/REMOVED/wp-content/plugins/distributor-master/includes/classes/InternalConnections/NetworkSiteConnection.php:39
Stack trace:
#0 /var/www/REMOVED/wp-content/plugins/distributor-master/includes/classes/InternalConnections/NetworkSiteConnection.php(496): Distributor\InternalConnections\NetworkSiteConnection->__construct(NULL)
#1 /var/www/REMOVED/wp-includes/class-wp-hook.php(288): Distributor\InternalConnections\NetworkSiteConnection::update_syndicated(6844)
#2 /var/www/REMOVED/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /var/www/REMOVED/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /var/www/REMOVED/wp-include" while reading response header from upstream, client: REMOVED, server: REMOVED.net.au, request: "POST /wp-admin/post.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "REMOVED.net.au", referrer: "https://REMOVED.net.au/wp-admin/post.php?post=6844&action=edit"
```

**Comment by jeffpaul** [comment]
@mitchmusarra apologies for the slow response; are you still seeing this error with Visual Composer-related distributed pages or can this be closed as resolved?

**Comment by jeffpaul** [comment]
@mitchmusarra any updates on your issue and whether its still occurring with Visual Composer?

**Comment by jeffpaul** [comment]
I'm closing this issue due to inactivity, but please let me know if you're still having problems so I can try to help... thanks!
