### ISSUE TITLE
Notice and fatal error connecting to site that requires login (Force Login plugin)

### ISSUE THREAD

**Issue by demetris** [10up/distributor#52]
```
Notice: Undefined index: post in /REMOVED/wp-content/plugins/distributor/includes/classes/ExternalConnections/WordPressExternalConnection.php on line 127

Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /REMOVED/wp-content/plugins/distributor/includes/classes/PullListTable.php:384

Stack trace:

#0 /REMOVED/wp-content/plugins/distributor/includes/pull-ui.php(297): Distributor\PullListTable->prepare_items()
#1 /REMOVED/wp-includes/class-wp-hook.php(286): Distributor\PullUI\dashboard('')
#2 /REMOVED/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /REMOVED/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /REMOVED/wp-admin/admin.php(224): do_action('distributor_pag...')
#5 {main} thrown in /REMOVED/wp-content/plugins/distributor/includes/classes/PullListTable.php on line 384
```

The above is displayed on the Pull Content screen when connecting to a site that uses the [Force Login](https://github.com/kevinvess/wp-force-login) plugin.

When the Force Login plugin is not active everything in Distributor works as expected .

I use the recommended authentication method (Application Passwords).

Connecting and posting to the site using cURL or Python Requests seems to work fine whether Force Login is active or not.

Let me know if you need any more information.

Cheers!

**Comment by jeffpaul** [comment]
@demetris are you still seeing the notice and fatal error or can we close this issue as resolved?

**Comment by jeffpaul** [comment]
I'm closing this issue due to inactivity, but please let me know if you're still having problems so I can try to help... thanks!
